services:
  gateway:
    image: gateway:latest
    ports:
      - "8081:8081"

  auth-service:
    image: auth-service:latest
    ports:
      - "9090:9090"

  echo-service:
    container_name: echo-service
    build:
      context: ./echoService/
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
