server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9090
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}

        - id: echo-service
          uri: http://echo-service:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1