server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:9090
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:9090
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}

        - id: quote-service
          uri: http://quote-service:8083
          predicates:
            - Path=/api/quotes/**
          filters:
            - StripPrefix=1

        - id: echo-service
          uri: http://echo-service:8082
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1